name: deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to production
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v4

    - name: Build container images
      run: |
        docker build -t ${{ github.repository }}:${{ github.sha }} .
        docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push images to Docker Hub
      run: |
        docker push ${{ github.repository }}:${{ github.sha }}
        docker push ${{ github.repository }}:latest

    - name: Deploying to Kubernetes
      uses: steebchen/kubectl@v2.1.1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/dectalk --namespace nitrixme dectalk=${{ github.repository }}:${{ github.sha }}

    - name: Verifying deployment rollout
      uses: steebchen/kubectl@v2.1.1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: rollout status deployment/dectalk --namespace nitrixme
